services:
  auth-service:
    container_name: auth-service
    build:
      context: ./auth-service
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
    environment:
      - SPRING_DATASOURCE_URL=${AUTH_SERVICE_DB_URL}
      - SPRING_DATASOURCE_USERNAME=${DB_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${DB_PASSWORD}
      - JWT_SECRET=${JWT_SECRET}
      - JWT_EXPIRATION=3600000
    depends_on:
      auth-db:
        condition: service_healthy
    networks:
      - app-network

  waterpolo-api:
    container_name: waterpolo-api
    build:
      context: ./waterpolo-api
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    environment:
      - SPRING_DATASOURCE_URL=${WATERPOLO_DB_URL}
      - SPRING_DATASOURCE_USERNAME=${DB_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${DB_PASSWORD}
      - JWT_SECRET=${JWT_SECRET}
    depends_on:
      waterpolo-db:
        condition: service_healthy
      auth-service:
        condition: service_started
    networks:
      - app-network

  auth-db:
    container_name: auth-db
    build:
      context: ./BBDD/auth-db
      dockerfile: Dockerfile
    ports:
      - "3307:3306"
#    volumes:
#      - auth-db-data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=auth_service_db
      - MYSQL_ROOT_HOST=%
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      retries: 5
      timeout: 5s

  waterpolo-db:
    container_name: waterpolo-db
    build:
      context: ./BBDD/waterpolo-db
      dockerfile: Dockerfile
    ports:
      - "3308:3306"
#    volumes:
#      - waterpolo-db-data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=waterpolo_db
      - MYSQL_ROOT_HOST=%
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      retries: 5
      timeout: 5s

networks:
  app-network:
    driver: bridge

#volumes:
#    auth-db-data:
#    waterpolo-db-data: